name: Radar Update Script

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests rasterio geopandas shapely

      - name: Run Python Script
        run: |
          mkdir -p data
          python update_data.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/pioggia_veneto.json
          git commit -m "Aggiornamento radar automatico" || echo "Nessuna modifica rilevata"
          git push
